---
name: cmpsc-580-Spring-2022-Assignment5
break: true
indent: 4
---

# --> check the technical writing
writing/report.md:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "Add Your Account Name Here" --count 0 --exact
    MatchFileFragment --fragment "Add Your Research Book Link Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact


writing/interview.md:
    ConfirmFileExists
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "Add Your Account Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact


# --> check the number of commits beyond a threshold
CountCommits --count 3
